# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add the following block for proxying API requests
[[redirects]]
  from = "/api/*"
  to = "https://3.145.48.19:3000/api/:splat"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  command = "pip install -r requirements.txt && python main.py"
  python_version = "3.11"
